{"ray": {"sid": "a0bf4626b07e4e1583ef8feedc5f4d47", "uid": null, "qid": "46d2b12d3c0244389e1f85fc3c646890", "rid": null, "bars": {"default": {"percent": "100", "remaining": "0"}}, "messages": [{"type": "ERROR", "content": "process - failed executing: [46d2b12d3c0244389e1f85fc3c646890]\nTraceback (most recent call last):\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/openfabric_pysdk/app/worker.py\", line 90, in process\n    output = execution_callback_function(data, ray, self.state)\n  File \"/home/youseef/openfabric/openfabric-ai-software-engineer/openfabric-ai-software-engineer/main.py\", line 84, in execute\n    answer = qa_model(text, context)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"/home/youseef/openfabric/openfabric-ai-software-engineer/openfabric-ai-software-engineer/main.py\", line 54, in forward\n    outputs = self.model.generate(**inputs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/utils/_contextlib.py\", line 115, in decorate_context\n    return func(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/generation/utils.py\", line 1593, in generate\n    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/generation/utils.py\", line 742, in _prepare_encoder_decoder_kwargs_for_generation\n    model_kwargs[\"encoder_outputs\"]: ModelOutput = encoder(**encoder_kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/accelerate/hooks.py\", line 165, in new_forward\n    output = module._old_forward(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/transformers/models/t5/modeling_t5.py\", line 1016, in forward\n    inputs_embeds = self.embed_tokens(input_ids)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\n    return self._call_impl(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\n    return forward_call(*args, **kwargs)\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/modules/sparse.py\", line 162, in forward\n    return F.embedding(\n  File \"/home/youseef/anaconda3/envs/openfabric/lib/python3.8/site-packages/torch/nn/functional.py\", line 2233, in embedding\n    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)\nRuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument index in method wrapper_CUDA__index_select)\n", "created_at": "2023-12-14T03:26:22.856283"}], "status": "FAILED", "created_at": "2023-12-14T03:26:12.079510", "updated_at": "2023-12-14T03:26:22.857647", "finished": true}, "in": {"text": ["What is the capital of Egypt?"]}, "out": {}}